version: '3.2'

services:
    composer:
      build: docker/composer
      container_name: bitmanage-composer
      volumes:
          - .:/application

    webserver:
      image: nginx:alpine
      container_name: bitmanage-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "7717:80"
      links:
       - php-fpm
       - composer

    php-fpm:
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      container_name: bitmanage-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        - ./docker/php-fpm/app_dev.php:/application/web/app_dev.php